/**
*	@Author: Allan Pecli
*	@Company: HCL Technologies
*	@Class: Data class for Quote's Object.
*	@Comments: 
*	@Created Date: 07/12/2021
*
*	------------------------------------------------------------------------------------------
*	Modification Log:
*	==========================================================================================
*	@Version		@Author			@Date			@Reason
*    ---             Lucas Silva    08/04/2024      Commented class - TO DO: Remove this class
*                                                   from org once that is no used anymore.
*	==========================================================================================
*/
public class QuoteDAO {
    /*private static final QuoteDAO instance = new QuoteDAO();    
    private QuoteDAO(){}
    
    public static QuoteDAO getInstance() {
        return instance;
    }
    public List<Quote> getQuoteListInfobyIds(Set<Id> quoteIds)
    {
        return [SELECT Id, Tax, ShippingPostalCode, ShippingStateCode, ShippingHandling, TotalPrice FROM Quote 
                WHERE Id IN:quoteIds];
    }*/
}